<template>
  <div ref="chartContainer" class="chart-container">
    <div v-show="!dataSources" class="warning data-view-warning">
      没有数据可以构建图表。请运行您的SQL查询并确保结果不为空。
    </div>
    <div
      class="chart"
      :style="{ height: !dataSources ? 'calc(100% - 40px)' : '100%' }"
    >
      <PlotlyEditor
        ref="plotlyEditor"
        :data="state.data"
        :layout="state.layout"
        :frames="state.frames"
        :config="config"
        :dataSources="dataSources"
        :dataSourceOptions="dataSourceOptions"
        :plotly="plotly"
        :useResizeHandler="useResizeHandler"
        :debug="true"
        :advancedTraceTypeSelector="true"
        :hideControls="!showViewSettings"
        :locale="'zh'"
        :dictionaries="chartDictionaries"
        @update="update"
        @render="onRender"
      />
    </div>
  </div>
</template>

<script>
import ReactPlotlyEditorWithPlotRef from '@/lib/ReactPlotlyEditorWithPlotRef.jsx'
import chartHelper from '@/lib/chartHelper'
import events from '@/lib/utils/events'
import fIo from '@/lib/utils/fileIo'
import plotly from 'plotly.js'
import zhCN from 'plotly.js/lib/locales/zh-cn'
import * as dereference from 'react-chart-editor/lib/lib/dereference'
import 'react-chart-editor/lib/react-chart-editor.css'
import { applyPureReactInVue } from 'veaury'

export default {
  name: 'Chart',
  components: {
    PlotlyEditor: applyPureReactInVue(ReactPlotlyEditorWithPlotRef)
  },
  props: {
    dataSources: Object,
    initOptions: Object,
    exportToPngEnabled: Boolean,
    exportToSvgEnabled: Boolean,
    forPivot: Boolean,
    showViewSettings: Boolean
  },
  emits: [
    'update:exportToSvgEnabled',
    'update:exportToHtmlEnabled',
    'update',
    'loadingImageCompleted'
  ],
  data() {
    return {
      plotly,
      state: this.initOptions || {
        data: [],
        layout: { autosize: true },
        frames: []
      },
      config: {
        editable: true,
        displaylogo: false,
        modeBarButtonsToRemove: ['toImage'],
        locale: 'zh-CN'
      },
      resizeObserver: null,
      useResizeHandler: this.$store.state.isWorkspaceVisible,
      chartDictionaries: {
        zh: {
          'Trace your data.': '追踪您的数据。',
          'Traces of various types like bar and line are the building blocks of your figure.': '各种类型的轨迹（如柱状图和折线图）是您图表的构建块。',
          'You can add as many as you like, mixing and matching types and arranging them into subplots.': '您可以添加任意数量，混合匹配类型并将它们排列到子图中。',
          'Click on the + button above to add a trace.': '点击上方的+按钮添加轨迹。',
          'Call out your data.': '标注您的数据。',
          'Annotations are text and arrows you can use to point out specific parts of your figure.': '注释是您可以用来指向图表特定部分的文本和箭头。',
          'Click on the + button above to add an annotation.': '点击上方的+按钮添加注释。',
          'Looks like there aren\'t any traces defined yet.': '看起来还没有定义任何轨迹。',
          'Go to the Traces panel under Structure to define traces.': '转到结构下的轨迹面板来定义轨迹。',
          'Lines, Rectangles and Ellipses.': '线条、矩形和椭圆。',
          'Add shapes to a figure to highlight points or periods in time, thresholds, or areas of interest.': '向图表中添加形状以突出显示时间点或时间段、阈值或感兴趣的区域。',
          'Click on the + button above to add a shape.': '点击上方的+按钮添加形状。',
          'Trace': '轨迹',
          'Traces': '轨迹',
          'Add Trace': '添加轨迹',
          'Choose Plot Type': '选择图表类型',
          'Select Trace Type': '选择轨迹类型',
          'General': '常规',
          'Defaults': '默认值',
          'Modebar': '模式栏',
          'shapes': '形状',
          'images': '图片',
          'Subplots': '子图',
          'Style': '样式',
          'Annotate': '注释',
          'Images': '图片',
          'Shapes': '形状',
          'Shape': '形状',
          'Image': '图片',
          'Add Shape': '添加形状',
          'Add Image': '添加图片',
          'Edit Shape': '编辑形状',
          'Edit Image': '编辑图片',
          'Delete Shape': '删除形状',
          'Delete Image': '删除图片',
          'Type': '类型',
          'Coordinates': '坐标',
          'Style': '样式',
          'Position': '位置',
          'Size': '大小',
          'Rotation': '旋转',
          'Opacity': '透明度',
          'Border': '边框',
          'Fill': '填充',
          'Color': '颜色',
          'Width': '宽度',
          'Height': '高度',
          'URL': 'URL',
          'Source': '源',
          'Align': '对齐',
          'Layer': '图层',
          'Scale': '缩放',
          'Aspect Ratio': '纵横比',
          'Constrain Aspect': '约束纵横比',
          'Lock Aspect': '锁定纵横比',
          'Line': '线条',
          'Rectangle': '矩形',
          'Ellipse': '椭圆',
          'Circle': '圆形',
          'Arrow': '箭头',
          'Open': '开放',
          'Closed': '封闭',
          'Dash': '虚线',
          'Solid': '实线',
          'Dot': '点',
          'Dashdot': '点划线',
          'Dashdotdot': '双点划线',
          'Round': '圆形',
          'Square': '方形',
          'Butt': '平头',
          'Auto': '自动',
          'X': 'X',
          'Y': 'Y',
          'X0': 'X0',
          'Y0': 'Y0',
          'X1': 'X1',
          'Y1': 'Y1',
          'Center': '中心',
          'Radius': '半径',
          'Start': '开始',
          'End': '结束',
          'Head': '头部',
          'Tail': '尾部',
          'Length': '长度',
          'Showarrow': '显示箭头',
          'Arrowhead': '箭头头部',
          'Arrowwidth': '箭头宽度',
          'Arrowcolor': '箭头颜色',
          'Ax': 'Ax',
          'Ay': 'Ay',
          'A': 'A',
          'B': 'B',
          'C': 'C',
          'Visible': '可见',
          'Hoverinfo': '悬停信息',
          'Name': '名称',
          'UID': '唯一标识',
          'Templateitemname': '模板项名称',
          'Logos, watermarks and more.': '徽标、水印等。',
          'Embed images in your figure to make the data more readable or to brand your content.': '在图表中嵌入图片，使数据更易读或为内容添加品牌标识。',
          'Click on the + button above to add an image.': '点击上方的+按钮添加图片。',
          'Drop the image to upload here or click to choose a file from your computer.': '拖放图片到此处上传，或点击从您的电脑选择文件。',
          'Supported formats are: JPEG, JPG, SVG, SVG+XML, PNG, GIF, BMP, WEBP.': '支持的格式有：JPEG, JPG, SVG, SVG+XML, PNG, GIF, BMP, WEBP。',
          'Relative to Grid': '相对于网格',
          'Choose data...': '选择数据...',
          'Transforms': '转换',
          'new text': '新文本',
          'Rich Text': '富文本',
          'LaTeX': 'LaTeX',
          'Typeface': '字体',
          'Horizontal Alignment': '水平对齐',
          'X Offset': 'X偏移',
          'Y Offset': 'Y偏移',
          'X Vector': 'X向量',
          'Y Vector': 'Y向量',
          'Data': '数据',
          'Layout': '布局',
          'Style': '样式',
          'Analyze': '分析',
          'Export': '导出',
          'Update': '更新',
          'Run': '运行',
          'Stop': '停止',
          'Reset': '重置',
          'Start': '开始',
          'Show': '显示',
          'Hide': '隐藏',
          'Constant': '常量',
          'Variable': '变量',
          'Calculated': '计算',
          'Direct': '直接',
          'Map to': '映射到',
          'Normal': '正常',
          'Reversed': '反转',
          'Continuous': '连续',
          'Categorical': '分类',
          'Yes': '是',
          'No': '否',
          'Circular': '圆形',
          'Random': '随机',
          'Circle pack': '圆堆积',
          'ForceAtlas2': '力导向图',
          'Advanced layout settings': '高级布局设置',
          'Reset': '重置',
          'Min': '最小值',
          'Max': '最大值',
          'Scale': '缩放',
          'Degree': '度数',
          'In degree': '入度',
          'Out degree': '出度',
          'Color': '颜色',
          'Color as': '颜色作为',
          'Color scale': '颜色刻度',
          'Color scale direction': '颜色刻度方向',
          'Node': '节点',
          'Nodes': '节点',
          'Edge': '边',
          'Edges': '边',
          'Label': '标签',
          'Label color': '标签颜色',
          'Size': '大小',
          'Background color': '背景颜色',
          'Direction': '方向',
          'Algorithm': '算法',
          'Hierarchy attributes': '层级属性',
          'Seed value': '种子值',
          'Weight source': '权重源',
          'Initial iterations amount': '初始迭代次数',
          'Adjust sizes': '调整大小',
          'Barnes Hut optimize': 'Barnes Hut优化',
          'Barnes Hut theta': 'Barnes Hut theta',
          'Edge weight influence': '边权重影响',
          'Gravity': '重力',
          'Lin Log mode': 'Lin Log模式',
          'Outbound attraction distribution': '外向吸引力分布',
          'Scaling ratio': '缩放比例',
          'Slow down': '减速',
          'Strong gravity mode': '强重力模式',
          'Map your result set records to node and edge properties required to build a graph.': '将结果集记录映射到构建图所需的节点和边属性。',
          'A field indicating if the record is node (value 0) or edge (value 1).': '指示记录是节点（值为0）还是边（值为1）的字段。',
          'A field keeping unique node identifier.': '保存唯一节点标识符的字段。',
          'A field keeping a node identifier where the edge starts.': '保存边开始节点标识符的字段。',
          'A field keeping a node identifier where the edge ends.': '保存边结束节点标识符的字段。',
          'No Results': '无结果',
          'Select an Option': '选择一个选项',
          'Structure': '结构',
          'Subplots': '子图',
          'Annotate': '注释',
          'Annotation': '注释',
          'Annotations': '注释',
          'Add Annotation': '添加注释',
          'X': 'X轴',
          'Y': 'Y轴',
          'Z': 'Z轴',
          'Title': '标题',
          'Subtitle': '副标题',
          'Axis': '坐标轴',
          'Axes': '坐标轴',
          'Legend': '图例',
          'Grid': '网格',
          'Margin': '边距',
          'Font': '字体',
          'Tick': '刻度',
          'Ticks': '刻度',
          'Range': '范围',
          'Type': '类型',
          'Log': '对数',
          'Linear': '线性',
          'Date': '日期',
          'Category': '类别',
          'Angle': '角度',
          'Position': '位置',
          'Alignment': '对齐',
          'Horizontal': '水平',
          'Vertical': '垂直',
          'Left': '左',
          'Right': '右',
          'Top': '上',
          'Bottom': '下',
          'Center': '居中',
          'Width': '宽度',
          'Height': '高度',
          'Opacity': '透明度',
          'Thickness': '厚度',
          'Dash': '虚线',
          'Solid': '实线',
          'Dot': '点',
          'Dashdot': '点划线',
          'Dashdotdot': '双点划线',
          'Round': '圆形',
          'Square': '方形',
          'Diamond': '菱形',
          'Cross': '十字',
          'X-cross': 'X十字',
          'Pentagon': '五边形',
          'Hexagon': '六边形',
          'Octagon': '八边形',
          'Star': '星形',
          'Triangle-up': '上三角形',
          'Triangle-down': '下三角形',
          'Triangle-left': '左三角形',
          'Triangle-right': '右三角形',
          'Arrow': '箭头',
          'Lines': '线条',
          'Markers': '标记',
          'Text': '文本',
          'Bar': '柱状图',
          'Line': '折线图',
          'Scatter': '散点图',
          'Area': '面积图',
          'Pie': '饼图',
          'Donut': '环形图',
          'Histogram': '直方图',
          'Box': '箱线图',
          'Violin': '小提琴图',
          'Contour': '等高线图',
          'Heatmap': '热力图',
          'Surface': '曲面图',
          'Mesh': '网格图',
          '3D Scatter': '3D散点图',
          '3D Line': '3D折线图',
          '3D Surface': '3D曲面图',
          'Choropleth': '地图',
          'Table': '表格',
          'Image': '图片',
          'Candlestick': '蜡烛图',
          'OHLC': 'K线图',
          'Waterfall': '瀑布图',
          'Funnel': '漏斗图',
          'Funnel Area': '漏斗面积图',
          'Indicator': '指标图',
          'Polar': '极坐标图',
          'Radar': '雷达图',
          'Sankey': '桑基图',
          'Sunburst': '旭日图',
          'Treemap': '树状图',
          'Parallel Coordinates': '平行坐标图',
          'Scatter Matrix': '散点矩阵图',
          'Error Bars': '误差线',
          'Box Select': '框选',
          'Lasso Select': '套索选择',
          'Zoom': '缩放',
          'Pan': '平移',
          'Go to the': '转到',
          'panel under Structure to define traces.': '结构面板下定义轨迹。',
          'Autoscale': '自动缩放',
          'Reset Axes': '重置坐标轴',
          'Toggle Spike Lines': '切换峰值线',
          'Show Closest Data on Hover': '悬停时显示最近数据',
          'Compare Data on Hover': '悬停时比较数据',
          'Save': '保存',
          'Copy': '复制',
          'Download': '下载',
          'Share': '分享',
          'Embed': '嵌入',
          'Fullscreen': '全屏',
          'Settings': '设置',
          'Help': '帮助',
          'About': '关于',
          'Close': '关闭',
          'Apply': '应用',
          'Cancel': '取消',
          'OK': '确定',
          'Delete': '删除',
          'Duplicate': '复制',
          'Move': '移动',
          'Rename': '重命名',
          'Edit': '编辑',
          'Add': '添加',
          'Remove': '移除',
          'Clear': '清除',
          'Select': '选择',
          'Deselect': '取消选择',
          'All': '全部',
          'None': '无',
          'Custom': '自定义',
          'Default': '默认',
          'Auto': '自动',
          'Manual': '手动',
          'Advanced': '高级',
          'Basic': '基础',
          'Intermediate': '中级',
          'Primary': '主要',
          'Secondary': '次要',
          'Tertiary': '第三',
          'Quaternary': '第四',
          'Positive': '正向',
          'Negative': '负向',
          'Increasing': '递增',
          'Decreasing': '递减',
          'Ascending': '升序',
          'Descending': '降序',
          'Average': '平均',
          'Mean': '均值',
          'Median': '中位数',
          'Mode': '众数',
          'Range': '范围',
          'Min': '最小值',
          'Max': '最大值',
          'Sum': '总和',
          'Count': '计数',
          'Total': '总计',
          'Percent': '百分比',
          'Percentage': '百分比',
          'Ratio': '比例',
          'Rate': '比率',
          'Change': '变化',
          'Difference': '差异',
          'Delta': '增量',
          'Growth': '增长',
          'Trend': '趋势',
          'Forecast': '预测',
          'Fit': '拟合',
          'Filter': '筛选',
          'Sort': '排序',
          'Group': '分组',
          'Aggregate': '聚合',
          'Calculate': '计算',
          'Transform': '转换',
          'Bin': '分箱',
          'Bin Size': '分箱大小',
          'Number of Bins': '分箱数量',
          'Histogram Mode': '直方图模式',
          'Stack': '堆叠',
          'Overlay': '叠加',
          'Group': '分组',
          'Relative': '相对',
          'Percent': '百分比',
          'Density': '密度',
          'Cumulative': '累积',
          'Orientation': '方向',
          'Horizontal': '水平',
          'Vertical': '垂直',
          'Spacing': '间距',
          'Gap': '间隙',
          'Width': '宽度',
          'Offset': '偏移',
          'Base': '基准线',
          'Line Style': '线条样式',
          'Marker Style': '标记样式',
          'Fill': '填充',
          'Fill Color': '填充颜色',
          'Line Color': '线条颜色',
          'Marker Color': '标记颜色',
          'Line Width': '线条宽度',
          'Marker Size': '标记大小',
          'Opacity': '透明度',
          'Hover': '悬停',
          'Hover Text': '悬停文本',
          'Hover Info': '悬停信息',
          'Show Legend': '显示图例',
          'Legend Position': '图例位置',
          'Legend Orientation': '图例方向',
          'Legend Title': '图例标题',
          'Grid Lines': '网格线',
          'Major Grid': '主网格',
          'Minor Grid': '次网格',
          'Zero Line': '零线',
          'Spike Lines': '峰值线',
          'Tick Labels': '刻度标签',
          'Tick Marks': '刻度标记',
          'Tick Format': '刻度格式',
          'Tick Angle': '刻度角度',
          'Tick Length': '刻度长度',
          'Tick Width': '刻度宽度',
          'Axis Title': '坐标轴标题',
          'Axis Line': '坐标轴线条',
          'Axis Width': '坐标轴宽度',
          'Axis Color': '坐标轴颜色',
          'Background': '背景',
          'Paper': '画布',
          'Plot': '绘图区域',
          'Border': '边框',
          'Margin Left': '左边距',
          'Margin Right': '右边距',
          'Margin Top': '上边距',
          'Margin Bottom': '下边距',
          'Margin Pad': '内边距',
          'Annotation Text': '注释文本',
          'Annotation Position': '注释位置',
          'Annotation Arrow': '注释箭头',
          'Arrow Head': '箭头头部',
          'Arrow Length': '箭头长度',
          'Arrow Width': '箭头宽度',
          'Arrow Color': '箭头颜色',
          'Font Family': '字体',
          'Font Size': '字体大小',
          'Font Color': '字体颜色',
          'Font Weight': '字体粗细',
          'Font Style': '字体样式',
          'Bold': '粗体',
          'Italic': '斜体',
          'Underline': '下划线',
          'Strikethrough': '删除线',
          'Superscript': '上标',
          'Subscript': '下标',
          'Text Alignment': '文本对齐',
          'Text Position': '文本位置',
          'Text Angle': '文本角度',
          'Text Color': '文本颜色',
          'Text Size': '文本大小',
          'Text Style': '文本样式',
          'Text Font': '文本字体',
          'Mode Bar': '模式栏',
          'Display Mode Bar': '显示模式栏',
          'Mode Bar Position': '模式栏位置',
          'Scroll Zoom': '滚动缩放',
          'Double Click': '双击',
          'Double Click to Zoom': '双击缩放',
          'Pan on Drag': '拖动平移',
          'Zoom on Wheel': '滚轮缩放',
          'Zoom on Double Click': '双击缩放',
          'Box Select on Drag': '拖动框选',
          'Lasso Select on Drag': '拖动套索选择',
          'Display Logo': '显示Logo',
          'Display Watermark': '显示水印',
          'Responsive': '响应式',
          'Static': '静态',
          'Interactive': '交互式',
          'Animations': '动画',
          'Animation': '动画',
          'Frames': '帧',
          'Frame': '帧',
          'Play': '播放',
          'Pause': '暂停',
          'Loop': '循环',
          'Autoplay': '自动播放',
          'Duration': '持续时间',
          'Transition': '过渡',
          'Easing': '缓动',
          'Linear': '线性',
          'Quad': '二次',
          'Cubic': '三次',
          'Quart': '四次',
          'Quint': '五次',
          'Sine': '正弦',
          'Expo': '指数',
          'Circ': '圆形',
          'Back': '回弹',
          'Bounce': '弹跳',
          'Elastic': '弹性',
          'In': '进入',
          'Out': '退出',
          'InOut': '进入退出',
          'Scale': '缩放',
          'Translate': '平移',
          'Rotate': '旋转',
          'Opacity': '透明度',
          'Colorscale': '颜色刻度',
          'Colorscales': '颜色刻度',
          'Color Range': '颜色范围',
          'Color Axis': '颜色轴',
          'Color Bar': '颜色条',
          'Color Bar Title': '颜色条标题',
          'Color Bar Position': '颜色条位置',
          'Color Bar Orientation': '颜色条方向',
          'Color Bar Thickness': '颜色条厚度',
          'Color Bar Length': '颜色条长度',
          'Color Bar Ticks': '颜色条刻度',
          'Color Bar Tick Labels': '颜色条刻度标签',
          'Color Bar Tick Format': '颜色条刻度格式',
          'Color Bar Tick Angle': '颜色条刻度角度',
          'Color Bar Tick Length': '颜色条刻度长度',
          'Color Bar Tick Width': '颜色条刻度宽度',
          'Color Bar Border': '颜色条边框',
          'Color Bar Border Width': '颜色条边框宽度',
          'Color Bar Border Color': '颜色条边框颜色',
          'Color Bar Background': '颜色条背景',
          'Color Bar Font': '颜色条字体',
          'Color Bar Font Size': '颜色条字体大小',
          'Color Bar Font Color': '颜色条字体颜色',
          'Color Bar Font Weight': '颜色条字体粗细',
          'Color Bar Font Style': '颜色条字体样式',
          'Color Bar Text Alignment': '颜色条文本对齐',
          'Color Bar Text Position': '颜色条文本位置',
          'Color Bar Text Angle': '颜色条文本角度',
          'Color Bar Text Color': '颜色条文本颜色',
          'Color Bar Text Size': '颜色条文本大小',
          'Color Bar Text Style': '颜色条文本样式',
          'Color Bar Text Font': '颜色条文本字体',
          'Simple': '简单',
          'Finance': '金融',
          'Distributions': '分布',
          'Maps': '地图',
          'Specialized': '专业',
          '3D': '3D',
          'Hidden': '隐藏',
          '3D Mesh': '3D网格图',
          'Cone': '锥图',
          'Streamtube': '流管图',
          '2D Histogram': '2D直方图',
          '2D Contour Histogram': '2D等高线直方图',
          'Tile Map': '瓦片地图',
          'Atlas Map': '地图集',
          'Choropleth Tile Map': '瓦片填充地图',
          'Choropleth Atlas Map': '地图集填充地图',
          'Density Tile Map': '密度瓦片地图',
          'Polar Scatter': '极坐标散点图',
          'Polar Bar': '极坐标柱状图',
          'Ternary Scatter': '三元散点图',
          '3D Line': '3D折线图',
          'Heatmap GL': '热力图GL',
          'Point Cloud': '点云图',
          'Parallel Categories': '平行类别图',
          'Scatterplot Matrix': '散点图矩阵',
          'Scatter Carpet': '散点地毯图',
          'Contour Carpet': '等高线地毯图',
          'Carpet': '地毯图',
          'Isosurface': '等值面图',
          'trace': '轨迹',
          'Rendering': '渲染',
          'Drop the geojson to upload here or click to choose a file from your computer.': '拖放geojson文件到此处上传，或点击从您的电脑选择文件。',
          'Supported formats are: APPLICATION/JSON.': '支持的格式有：APPLICATION/JSON。',
          'Lat/Lon': '经纬度',
          'Latitude': '纬度',
          'Longitude': '经度',
          'Location': '位置',
          'Locations': '位置',
          'Location Format': '位置格式',
          'Values': '值',
          'Headers': '表头',
          'Columns': '列',
          'Header Options': '表头选项',
          'Cell Options': '单元格选项',
          'Column Options': '列选项',
          'Order': '顺序',
          'Labels': '标签',
          'X Values': 'X值',
          'Y Values': 'Y值',
          'Note: in vertical orientation, X values are used for binning. If Y values are provided, they are used as inputs to the histogram function which you can configure in the': '注意：在垂直方向上，X值用于分箱。如果提供了Y值，它们将用作直方图函数的输入，您可以在',
          'panel under Style. If Y values are omitted, the histogram function defaults to Count.': '样式面板下配置。如果省略Y值，直方图函数默认为计数。',
          'Click to enter Plot title': '点击输入图表标题',
          'Click to enter Plot subtitle': '点击输入图表副标题',
          'Click to enter X axis title': '点击输入X轴标题',
          'Click to enter Y axis title': '点击输入Y轴标题',
          'Zoom': '缩放',
          'Pan': '平移',
          'Z Values': 'Z值',
          'Options': '选项',
          'I (Optional)': 'I（可选）',
          'J (Optional)': 'J（可选）',
          'K (Optional)': 'K（可选）',
          'Intensity': '强度',
          'Facecolor': '面颜色',
          'Vertexcolor': '顶点颜色',
          'Sources': '源',
          'Targets': '目标',
          'Source': '源',
          'Target': '目标',
          'Click to enter Plot subtitle': '点击输入图表副标题',
          'unrecognized GUI edit: title.subtitle.text': '无法识别的GUI编辑：title.subtitle.text',
          'Groups': '组',
          'Links': '链接',
          'Parents': '父级',
          'Collapse All': '全部折叠',
          'Expand All': '全部展开',
          'High': '高',
          'Low': '低',
          'Measure': '度量',
          'Theta': 'θ',
          'Go to the': '转到',
          'panel under Structure to define traces.': '结构面板下定义轨迹。',
          'Size and Margins': '大小和边距',
          'Plot Background': '图表背景',
          'Margin Color': '边距颜色',
          'Sequential': '顺序',
          'Diverging': '发散',
          'Negative Sequential': '负向顺序',
          'Base Font Size': '基础字体大小',
          'Number format': '数字格式',
          'Uniform Text Mode': '统一文本模式',
          'Padding': '内边距',
          'Interactions': '交互',
          'Drag': '拖动',
          'Click': '点击',
          'Click Event': '点击事件',
          'Select Data Point': '选择数据点',
          'Meta Text': '元文本',
          'Custom Data': '自定义数据',
          'You can refer to the items in this column in any text fields of the editor like so:': '您可以在编辑器的任何文本字段中引用此列中的项目，如下所示：',
          'My custom title': '我的自定义标题',
          'Ex:': '示例：',
          'Background Color': '背景颜色',
          'Border Color': '边框颜色',
          'Horizontal Position': '水平位置',
          'Icon Color': '图标颜色',
          'Active Icon Color': '激活图标颜色',
          'Titles': '标题',
          'Zoom Interactivity': '缩放交互',
          'Grid Spacing': '网格间距',
          'Max Number of Lines': '最大行数',
          'Auto margins': '自动边距',
          'Label Format': '标签格式',
          'Separate Thousands': '千位分隔符',
          'Exponents': '指数',
          'Show Exponents': '显示指数',
          'Prefix': '前缀',
          'Suffix': '后缀',
          'Tick Spacing': '刻度间距',
          'Max Number of Labels': '最大标签数',
          'Tick Markers': '刻度标记',
          'Range Slider': '范围滑块',
          'Inside': '内部',
          'Outside': '外部',
          'Enable': '启用',
          'Disable': '禁用',
          'Mirror Axis': '镜像轴',
          'Max Number of Markers': '最大标记数',
          'Border Width': '边框宽度',
          'Note Text': '注释文本',
          'Horizontal Positioning': '水平定位',
          'Anchor Point': '锚点',
          'Relative To': '相对于',
          'Vertical Positioning': '垂直定位',
          'Horizontal Boundaries': '水平边界',
          'Start Point': '起点',
          'End Point': '终点',
          'Vertical Boundaries': '垂直边界',
          'Relative to': '相对于',
          'Boundaries': '边界',
          'Snap to Grid': '对齐到网格',
          'X Anchor': 'X锚点',
          'Anchor to': '锚定到',
          'Side': '侧边',
          'Y Anchor': 'Y锚点',
          'Axes to Use': '使用的坐标轴',
          'X Axis': 'X轴',
          'Y Axis': 'Y轴',
          'You can style and position your axes in the': '您可以在以下位置设置坐标轴样式和位置',
          'panel': '面板'
        }
      }
    }
  },
  computed: {
    dataSourceOptions() {
      return chartHelper.getOptionsFromDataSources(this.dataSources)
    }
  },
  watch: {
    dataSources() {
      // we need to update state.data in order to update the graph
      // https://github.com/plotly/react-chart-editor/issues/948
      if (this.dataSources) {
        dereference.default(this.state.data, this.dataSources)
        this.updatePlotly()
      }
    },
    showViewSettings() {
      this.handleResize()
    }
  },
  created() {
    // 注册中文本地化
    plotly.register(zhCN)
    // https://github.com/plotly/plotly.js/issues/4555
    plotly.setPlotConfig({
      notifyOnLogging: 1
    })
    this.$watch(
      () =>
        this.state &&
        this.state.data &&
        this.state.data
          .map(trace => `${trace.type}${trace.mode ? '-' + trace.mode : ''}`)
          .join(','),
      value => {
        events.send('viz_plotly.render', null, {
          type: value,
          pivot: !!this.forPivot
        })
      },
      { deep: true }
    )
    this.$emit('update:exportToSvgEnabled', true)
    this.$emit('update:exportToHtmlEnabled', true)
  },
  mounted() {
    this.resizeObserver = new ResizeObserver(this.handleResize)
    this.resizeObserver.observe(this.$refs.chartContainer)
    if (this.dataSources) {
      dereference.default(this.state.data, this.dataSources)
    }
    this.handleResize()
  },
  activated() {
    this.useResizeHandler = true
  },
  deactivated() {
    this.useResizeHandler = false
  },
  beforeUnmount() {
    this.resizeObserver.unobserve(this.$refs.chartContainer)
  },
  methods: {
    async handleResize() {
      // Call updatePlotly twice because there is a small gap (for scrolling?)
      //  on right and bottom of the plot.
      // After the second call it's good.
      this.updatePlotly()
      this.updatePlotly()
    },
    onRender() {
      // TODO: check changes and enable Save button if needed
    },
    update(data, layout, frames) {
      this.state = { data, layout, frames }
      this.$emit('update')
    },
    updatePlotly() {
      const plotComponent = this.$refs.plotlyEditor.plotComponentRef.current
      plotComponent.updatePlotly(
        true, // shouldInvokeResizeHandler
        plotComponent.props.onUpdate, // figureCallbackFunction
        false // shouldAttachUpdateEvents
      )
    },
    getOptionsForSave() {
      return chartHelper.getOptionsForSave(this.state, this.dataSources)
    },
    async saveAsPng() {
      const url = await this.prepareCopy()
      this.$emit('loadingImageCompleted')
      fIo.downloadFromUrl(url, 'chart')
    },

    async saveAsSvg() {
      const url = await this.prepareCopy('svg')
      fIo.downloadFromUrl(url, 'chart')
    },

    saveAsHtml() {
      fIo.exportToFile(
        chartHelper.getHtml(this.state),
        'chart.html',
        'text/html'
      )
    },
    prepareCopy(type = 'png') {
      return chartHelper.getImageDataUrl(this.$refs.plotlyEditor.$el, type)
    }
  }
}
</script>

<style scoped>
.chart-container {
  height: 100%;
}

.chart {
  min-height: 242px;
}

:deep(.editor_controls .sidebar__item:before) {
  width: 0;
}
</style>
